// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RendaFixa.Infrastruct.Context;

#nullable disable

namespace RendaFixa.Infrastruct.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240929023824_cliente")]
    partial class cliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RendaFixa.Domain.Entities.Aporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaId")
                        .HasColumnType("uniquidentifier")
                        .HasColumnName("conta_fk");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_operacao");

                    b.Property<int>("RendaFixaId")
                        .HasColumnType("uniquidentifier")
                        .HasColumnName("renda_fixa_fk");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("RendaFixaId");

                    b.ToTable("aporte", (string)null);
                });

            modelBuilder.Entity("RendaFixa.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("RendaFixa.Domain.Entities.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("uniquidentifier")
                        .HasColumnName("cliente_fk");

                    b.Property<int>("CodigoConta")
                        .HasColumnType("int")
                        .HasColumnName("codigo_conta");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("conta", (string)null);
                });

            modelBuilder.Entity("RendaFixa.Domain.Entities.ProdutoRendaFixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estoque")
                        .HasColumnType("int")
                        .HasColumnName("estoque");

                    b.Property<string>("Indexador")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("indexador");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal")
                        .HasColumnName("preco_unitario");

                    b.Property<decimal>("Taxa")
                        .HasColumnType("decimal")
                        .HasColumnName("taxa");

                    b.HasKey("Id");

                    b.ToTable("produto_renda_fixa", (string)null);
                });

            modelBuilder.Entity("RendaFixa.Domain.Entities.Aporte", b =>
                {
                    b.HasOne("RendaFixa.Domain.Entities.Conta", "Conta")
                        .WithMany("Aportes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RendaFixa.Domain.Entities.ProdutoRendaFixa", "RendaFixa")
                        .WithMany("Aportes")
                        .HasForeignKey("RendaFixaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("RendaFixa");
                });

            modelBuilder.Entity("RendaFixa.Domain.Entities.Conta", b =>
                {
                    b.HasOne("RendaFixa.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Contas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("RendaFixa.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("RendaFixa.Domain.Entities.Conta", b =>
                {
                    b.Navigation("Aportes");
                });

            modelBuilder.Entity("RendaFixa.Domain.Entities.ProdutoRendaFixa", b =>
                {
                    b.Navigation("Aportes");
                });
#pragma warning restore 612, 618
        }
    }
}
